### ISSUE TITLE
"Unfortunately, you can't run this app" on several Android phones

### ISSUE THREAD

**Issue by SherylHYX** [nhsx/covid-19-app-android-ag-public#28]
**Describe the bug**

**To Reproduce**
1. Go to 'NHS covid 19' (I have also tried to give as many permissions as I can to this app)
2. Click on 'Continue'->'I Am OVER 16'
3. Scroll down to 'I agree'
4. Enter my postcode district
5. Click on 'Continue'
6. See error: 'Unfortunately, you can't run this app. This could be due to: A restriction in your settings(for example, if this is a company phone). Another app on your phone is using the same technology and stopping this app from working.'

**Expected behavior**
Now the APP should function normally.

**Smartphone 1(Mi10 Ultra):**
 - Device: Mi10 Ultra
 - OS: MIUI, Android
 - Browser: Mi browser, BAIDU
 - Version: (Android) 10; MIUI 120.10Stable 12.0.10.0

**Smartphone 2(HUAWEI P20):**
 - Device: HUAWEI P20
 - OS: EMUI, Android
 - Browser: HUAWEI browser, BAIDU
 - Version: (Android) 10; EMUI version 10.0.0

**Smartphone 3(HUAWEI P9):**
 - Device: HUAWEI P9
 - OS: EMUI, Android
 - Browser: HUAWEI browser, BAIDU
 - Version: (Android) 8.0.0; EMUI version 8.0.0

**Additional context**
I have also tried to give as many permissions as I can to this app, but failed. I tried three phones, all failed.

**Comment by songchaow** [comment]
Same issue with me.
I compiled the app and debugged on my phone via Android Studio, when `GoogleExplosureNotificationApi::start()` was called at `uk/nhs/nhsx/covid19/android/app/exposure/ExposureNotificationManager.kt:L15`, an exception was raised with detail message: "17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39501), resolution=null, message=null}".
Perhaps the problem is more related to Google Exposure Notifications API's compatibility, not the app.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome feedback on device compatibility and issues at - https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. We are looking to broaden manufacturer support over time. Google Play Services is currently required to use the application.
As @paulchambers mentions - a self-built application will not have permission to use the EN API, as per the Exposure Notifications page at: https://www.google.com/covid19/exposurenotifications/ - "Only public health authorities can use this system. Access to the technology will be granted only to apps from public health authorities."
